function analyse_CheckSNR_over_time
%13/8/18
%Written by Xing. Loads MUA and SNR data from .mat file (generated by
%analyse_CheckSNR2.m), during presentation of fullscreen flashing
%checkerboard stimuli to analyse signals for visually evoked responses.
%Plots measurements of SNR across time, for each channel.

allSNR=[];
xval=[];
dateLabels=[];
% for dates=[1:2 4 6 9 11:13 16:18 20:23 25:28]
for dates=[1 4 6 9 11 16:18 20:22 25:28]%remove dates when two occur very close together
    switch(dates)
        case 1
            date='040717_B2';
            whichDir=2;
            best=0;
        case 2
            date='050717_B3';
            whichDir=2;
        case 3
            date='060717_B2';%data from instances 1 to 4 missing?
            whichDir=2;
        case 4
            date='110717_B3';
            whichDir=2;
            best=1;
        case 5
            date='180717_B1';%forgot to turn off impedance mode all instances
            whichDir=1;
            best=0;
        case 6
            date='200717_B7';
            whichDir=1;
            best=1;
        case 7
            date='210717_B4';%forgot to turn off impedance mode on CerePlex Ms connected to instance 1
            whichDir=1;
            best=1;
        case 8
            date='240717_B2';%strange noise on most instances
            whichDir=1;
            best=1;
        case 9
            date='250717_B2';
            whichDir=1;
            best=1;
        case 10
            date='260717_B3';%events missing from instance 6
            whichDir=1;
            best=1;
        case 11
            date='080817_B7';
            whichDir=1;
            best=1;
        case 12
            date='090817_B8';
            whichDir=1;
            best=1;
        case 13
            date='100817_B2';
            whichDir=1;
            best=1;
        case 14
            date='180817_B10';%ns6 file missing for instance 6
            whichDir=1;
            best=1;
        case 15
            date='230817_B20';%files missing
            whichDir=1;
        case 16
            date='240817_B39';
            whichDir=1;
        case 17
            date='290817_B48';
            whichDir=1;
        case 18
            date='200917_B2';
            whichDir=1;
            best=1;
        case 19
            date='061017_B6';%strange signals on some channels on instance 3
            whichDir=1;
            best=1;
        case 20
            date='091017_B2';
            whichDir=1;
            best=1;
        case 21
            date='201017_B32';
            whichDir=1;
            best=1;
        case 22
            date='240118_B2';
            whichDir=2;
            best=1;
        case 23
            date='250118_B1';
            whichDir=2;
            best=1;
        case 24
            date='260118_B10';%only recorded from instances 1 and 2
            whichDir=2;
            best=1;
        case 25
            date='280218_B1';
            whichDir=2;
            best=1;
        case 26
            date='080618_B1';
            whichDir=2;
            best=1;
        case 27
            date='020818_B1';%strange signals on instances 3 and 4
            whichDir=2;
            best=1;
        case 28
            date='070818_B1';
            whichDir=2;
            best=1;
    end
    topDir='X:\best';
    if best==0
        topDir='X:\other';
    end
    
    allInstanceInd=1:8;
    allSessionSNR=[];
    for instanceCount=1:length(allInstanceInd)
        instanceInd=allInstanceInd(instanceCount);
        instanceName=['instance',num2str(instanceInd)];
        clear channelSNR
        
        fileName=fullfile(topDir,date,['mean_MUA_',instanceName,'.mat']);
        load(fileName,'channelSNR');
        allSessionSNR=[allSessionSNR;channelSNR(1:128)'];%compile SNR values across recording sessions
    end
    allSNR=[allSNR allSessionSNR];
    formatIn = 'ddmmyy';
    xval=[xval datenum(date,formatIn)];
    dateLabels=[dateLabels cellstr(date(1:6))];
end
saveFileName='D:\data\results\allSNR_130818.mat';
save(saveFileName,'allSNR');

figure;
for chInd=1:size(allSNR,1)
    plot(xval,allSNR(chInd,:));
    hold on
end
xlabel('session')
ylabel('SNR');
title('SNRs on individual channels across time')
set(gca,'XTickLabels',dateLabels)
set(gca,'XTick',xval)
set(gca, 'FontSize', 8)
set(gca,'XTickLabelRotation',60)

figure;hold on
boxplot(allSNR,'positions',xval,'boxstyle','filled','labels',dateLabels);
set(gca, 'FontSize', 8)
set(gca,'XTickLabelRotation',60)
xlabel('date')
ylabel('SNR');
surgery=datenum('200417',formatIn);
xlim([surgery-5 xval(end)+5]);
plot([surgery surgery],[0 110],'r');
ylim([0 100])
lines = findobj(gcf, 'type', 'line', 'Tag', 'Median');
set(lines, 'Color', 'r','LineWidth',5);

for chInd=1:size(allSNR,1)
    meanCh(chInd)=mean(allSNR(chInd,:));
    stdCh(chInd)=std(allSNR(chInd,:));
    %     errorbar(1,meanCh,stdCh);
end
%sort channels according to mean SNR value:
figure;
[meanChSorted indSort]=sort(meanCh);
stdChSorted=stdCh(indSort);
hErr=errorbar(1:length(meanChSorted),meanChSorted,stdChSorted);
xlabel('channel number, sorted')
ylabel('mean SNR & SD (uA)')
title('mean SNRs on individual channels, over 4/7/17 - 7/8/18')
xlim([0 1025])
ylim([0 70])

figure;
hErr=errorbar(1:length(meanCh),meanCh,stdCh);
xlabel('channel number, sorted')
ylabel('mean SNR & SD (uA)')
title('mean SNRs on individual channels, over 4/7/17 - 7/8/18')
xlim([0 1025])
ylim([0 70])

figure;%box plot for size of standard deviation
boxplot(stdChSorted);
title('size of standard deviation on individual channels, over 4/7/17 - 7/8/18')

%identify channels with large SD values:
largeSDchs=find(stdCh>10);
arrayNumsRedo=goodArrays8to16(largeSDchs,7)';
electrodeNumsRedo=goodArrays8to16(largeSDchs,8)';

%identify channels with a large difference between the two most recent values and/or where thresholding was only carried out once:
largeDiffChs=find(diffCh>2);
oneDatapointChs=find(diffCh==0);
largeDiffChs=union(largeDiffChs,oneDatapointChs);
arrayNumsRedo=goodArrays8to16(largeDiffChs,7)';
electrodeNumsRedo=goodArrays8to16(largeDiffChs,8)';

pause=1;