function plot_SF_tuning
%Written by Xing on 21/8/18. Plots SF tuning figures, after activity is
%calculated by analyse_SFtune.m.
close all
date='080618_B4';
orientations=[0 45 90 135];
SFs=[0.5 1 2 4 8];
numOriConds=length(orientations);
numSFConds=length(SFs);
prefSFs=[];
load('X:\best\080618_B4\080618_B4_data\CheckSNR_080618_B4.mat')
best=1;
switch(date)
    case '080618_B4'
        whichDir=2;
        best=1;
end
if whichDir==1%local copy available
    topDir='D:\data';
elseif whichDir==2%local copy deleted; use server copy
    if best==1
        topDir='X:\best';
    elseif best==0
        topDir='X:\other';
    end
end

%load orientation tuning data:
fileName='X:\best\080618_B3\good_channels_preferred_orientations.mat';%load data generated by analyse_RForitune.m and combine_orientation_tuning.m
load(fileName,'allPrefOri');
numTunedChs=length(find(allPrefOri~=-1));
tunedChs=find(allPrefOri~=-1);
closestOris=interp1(orientations,orientations,allPrefOri,'nearest');
colInds={};%colInds=[{1:5} {6:10} {11:15} {16:20}];
for oriCond=1:numOriConds
    colInds=[colInds {(oriCond-1)*numSFConds+1:oriCond*numSFConds}];
end

allInstanceInd=1:8;
for instanceCount=1:length(allInstanceInd)
    instanceInd=allInstanceInd(instanceCount);
    instanceName=['instance',num2str(instanceInd)];      
    fileName=fullfile(topDir,date,['mean_MUA_',instanceName,'.mat']);
    load(fileName,'meanActCondOri');

    for channelInd=1:128
        subplotInd=mod(channelInd,24);
        if subplotInd==0
            subplotInd=24;
        end
        if subplotInd==1
            figure;
        end
        subplot(4,6,subplotInd);hold on
        for oriInd=1:numOriConds
            oriAct=meanActCondOri(channelInd,length(SFs)*(oriInd-1)+1:length(SFs)+(oriInd-1)*length(SFs));
            plot(1:numSFConds,oriAct);
            if subplotInd==1&&instanceInd==1
%                 legend('0','45','90','135','Location','westoutside');
                legend('0','45','90','135');
            end
        end
        ax=gca;
        ax.XTick=1:numSFConds;
        ax.XTickLabel={'0.5' '1' '2' '4' '8'};
        xlabel('SF');
        ylabel('MUA');
        channelInd1024=channelInd+128*(instanceInd-1);
        closestOri=closestOris(channelInd1024);%preferred orientation, as calculated by analyse_RForitune.m
        if ~isnan(closestOri)%if the channel is orientation-tuned, as identified by analyse_RForitune.m
            oriCondInd=find(orientations==closestOri);
            [maxAct SFInd]=max(meanActCondOri(channelInd,colInds{oriCondInd}));%identify SF that elicits highest activity levels, for the orientation that is closest to the preferred orientation
            plot(SFInd,maxAct,'go');
        else%if analyse_RForitune.m did not reveal clear orientation tuning preference
            reshapedAct=reshape(meanActCondOri(channelInd,:),[numSFConds,numOriConds])';
            actAverageAcrossOri=mean(reshapedAct,1);
            [maxAct SFInd]=max(actAverageAcrossOri);
            plot(SFInd,maxAct,'ro');
        end
        prefSFs(channelInd1024,1)=SFs(SFInd);
    end
    for figInd=1:ceil(128/24)
        figure(figInd)
        set(gcf,'PaperPositionMode','auto','Position',get(0,'Screensize'))
        pathname=fullfile(topDir,date,[instanceName,'_fig',num2str(figInd),'_SF_tuning']);
        if instanceInd~=1
%             print(pathname,'-dtiff');
        end
    end
    close all
end
fileName=fullfile(topDir,date,['preferred_SFs.mat']);
save(fileName,'prefSFs');

%draw histogram of preferred SFs
h=histogram(prefSFs);
bar(1:5,h.Values([1,2,4,8,15]));
ax=gca;
ax.XTick=1:numSFConds;
ax.XTickLabel={'0.5' '1' '2' '4' '8'};
pathname=fullfile(topDir,date,'histogram_pref_SF');
print(pathname,'-dtiff');

%draw plot of preferred orientations
rose(degtorad(allPrefOri(tunedChs)));
xlim([-180 180]);
ylim([0 180]);